// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:day_date/features/schedule/data/models/schedule_deviation_model.dart';
import 'package:day_date/features/schedule/data/models/task_target_model.dart';
import 'package:day_date/features/schedule/data/models/time_block_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DeviationTypeModelAdapter());
    registerAdapter(OffDayStrategyModelAdapter());
    registerAdapter(ScheduleDeviationModelAdapter());
    registerAdapter(TaskTargetModelAdapter());
    registerAdapter(TimeAffinityModelAdapter());
    registerAdapter(TimeBlockModelAdapter());
    registerAdapter(TimeBlockTypeModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DeviationTypeModelAdapter());
    registerAdapter(OffDayStrategyModelAdapter());
    registerAdapter(ScheduleDeviationModelAdapter());
    registerAdapter(TaskTargetModelAdapter());
    registerAdapter(TimeAffinityModelAdapter());
    registerAdapter(TimeBlockModelAdapter());
    registerAdapter(TimeBlockTypeModelAdapter());
  }
}
